//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ 生成的包含文件。
// 供 CoolFormat3.rc 使用
//
#define IDCANLE                         2
#define IDS_LANGEXT_DLG                 3
#define IDS_LANGEXT_DLG_TIP             4
#define IDS_LANGEXT_EDIT_DLG            5
#define IDS_LANGUAGE_EX                 6
#define IDS_LANGUAGEEXT_EX              7
#define IDS_REG_ERROR                   8
#define IDS_GOTOLINE_DLG                9
#define IDS_GOTOLINE_DLG_TIP            10
#define IDS_EDITSTYLE_DATA              11
#define ID_TAB_HTML                     12
#define ID_TAB_CODE                     13
#define IDS_HTML_TIP                    14
#define IDS_TELLBUG_TITLE               15
#define IDS_TELLBUG_TEXT                16
#define IDS_STRING_SET_CPP              17
#define IDS_STRING_SET_JAVA             18
#define IDS_STRING_SET_CSHARP           19
#define IDS_STRING_SET_HTML             20
#define IDS_STRING_SET_XML              21
#define IDS_STRING_CONFIGOK             22
#define IDS_STRING_CONFIGFAIL           23
#define IDS_STRING_CONFIGOUTOK          24
#define IDS_STRING_CONFIGOUTFAIL        25
#define IDS_STRING_LISTOUTOK            26
#define IDS_STRING_BATCHFINDFILES       27
#define IDS_STRING_BATCH_EMPTY          28
#define IDS_STRING_BATCH_QUEREN         29
#define IDS_STRING30                    30
#define IDS_STRING_BATCH_OVER           30
#define IDS_STRING_FILENAMES            31
#define IDS_STRING_TITLEFILE            32
#define IDS_STRING33                    33
#define IDS_STRING_TITLENEW             33
#define IDS_STRING_GOWUHUAN             34
#define IDS_MSG_GODEFAULTOUT            35
#define IDS_STRING36                    36
#define IDS_STRING_OUTPUT               36
#define IDS_STRING_UAT_UNDEF            37
#define IDS_STRING_UAT_TYPE             38
#define IDS_STRING_UAT_BACK             39
#define IDS_STRING_UAT_CUT              40
#define IDS_STRING_UAT_PASTE            41
#define IDS_STRING_UAT_DEL              42
#define IDS_STRING_UAT_DRAG             43
#define IDS_STRING_UAT_ENTER            44
#define IDS_STRING_UAT_INDENT           45
#define IDS_STRING_UAT_UNINDENT         46
#define IDS_STRING_UAT_TAB              47
#define IDS_STRING_UAT_REP              48
#define IDS_STRING_UAT_COMM             49
#define IDS_STRING_UAT_UNCOMM           50
#define IDS_STRING_UAT_TIDY             51
#define IDS_STRING_MENU_EDIT            52
#define IDS_STRING_MENU_HTML            53
#define IDS_STRING_ABOUTDESC            54
#define IDS_STRING_OPTIONS              55
#define IDS_STRING_NEEDFILE             56
#define IDS_STRING57                    57
#define IDS_STRING58                    58
#define IDS_STRING59                    59
#define IDS_STRING60                    60
#define IDS_STRING61                    61
#define IDS_STRING62                    62
#define IDS_STRING63                    63
#define IDS_STRING64                    64
#define IDS_STRING65                    65
#define IDS_STRING66                    66
#define IDS_STRING67                    67
#define IDS_STRING68                    68
#define IDS_STRING69                    69
#define IDS_STRING70                    70
#define IDS_STRING71                    71
#define IDS_STRING72                    72
#define IDS_STRING73                    73
#define IDS_STRING74                    74
#define IDS_STRING75                    75
#define IDS_STRING76                    76
#define IDS_STRING77                    77
#define IDS_STRING78                    78
#define IDS_STRING79                    79
#define IDS_STRING80                    80
#define IDS_STRING81                    81
#define IDS_STRING82                    82
#define IDS_STRING83                    83
#define IDS_STRING84                    84
#define IDS_STRING85                    85
#define IDS_STRING86                    86
#define IDS_STRING87                    87
#define IDS_STRING88                    88
#define IDS_STRING89                    89
#define IDS_STRING90                    90
#define IDS_STRING91                    91
#define IDS_STRING92                    92
#define IDS_STRING93                    93
#define IDS_STRING94                    94
#define IDS_STRING95                    95
#define IDS_STRING96                    96
#define IDS_STRING97                    97
#define IDS_STRING_BATCHFORMAT          98
#define IDS_STRING_COMMPOPULAR          99
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDS_STRING_COMMHIDDEN           100
#define IDS_MAIN_TOOLBAR                101
#define ID_STATUSBAR_PANE3              102
#define ID_STATUSBAR_PANE4              103
#define IDS_STATUS_LINK                 104
#define IDS_STATUS_AUTOR                105
#define IDS_STATUS_ROWCOL               106
#define IDS_WINDOWS_MANAGER             107
#define IDS_STATUS_CUR_RC               108
#define IDS_STATUS_QQ                   109
#define IDS_STATUS_CONTACT              110
#define IDS_DOC_UNSUPPORT               111
#define IDS_STRING_COMMALL              112
#define IDS_STRING_SETFORMATTER         113
#define IDS_STRING_CHANGEOPTIONS        114
#define IDS_STRING_CHANGEVISIT          115
#define IDS_STRING116                   116
#define IDS_STRING_LINKEUPDATE          116
#define IDS_STRING_BATCHEXIT            117
#define IDS_STRING_BATCHSELLANG         118
#define IDS_STRING_BATCHSELFILE         119
#define IDS_STRING_BATCHADD             120
#define IDS_STRING_BATCHLOADLIST        121
#define IDS_STRING_BATCHSAVELIST        122
#define IDS_STRING_BATCHDROPTIP         123
#define IDS_STRING_POPULARTITLE         124
#define IDS_STRING_POPULARCOLOR         125
#define IDS_STRING_POPULARSCREEN        126
#define IDS_STRING_POPULARLANG          127
#define IDR_MAINFRAME                   128
#define IDR_CoolFormat3TYPE             129
#define IDS_STRING_POPULARCOLORSTR      130
#define IDR_POPUP_TOOLBAR               131
#define IDS_STRING_POPULARSCRSTR        131
#define IDR_POPUP_MDITABS               132
#define IDS_STRING_RES_UPDATE           132
#define IDR_POPUP_DROP_MDITABS          133
#define IDS_STRING_RES_LINKEME          133
#define IDR_PASTE_MENU                  134
#define IDS_STRING_RES_TITLE            134
#define IDR_WINDOWS_MENU                135
#define IDS_STRING_RES_CHECKUP          135
#define IDR_THEME_MENU                  136
#define IDS_STRING_RES_ABOUTLB          136
#define IDS_STRING_RES_ABOUT            137
#define IDS_STR_VIEWFORMATTER           138
#define IDS_STRING_VIEWDESC             139
#define IDS_STRING140                   140
#define IDS_STRING_WUHUAN               140
#define IDS_STRING_CHANGELANG           141
#define IDS_STRING141                   141
#define IDS_STRING_HTML_AUTOCOPY        142
#define IDS_STRING142                   142
#define IDS_STRING_VERSION              143
#define IDS_STRING_COPYCODE             144
#define IDS_STRING144                   144
#define IDB_RIBBON_ICONS                154
#define IDB_RIBBON_FILESMALL            155
#define IDB_RIBBON_FILELARGE            156
#define IDB_RIBBON_HOMESMALL            157
#define IDB_RIBBON_HOMELARGE            158
#define IDR_CONTEXT_MENU                160
#define IDR_EDIT_CONTEXT_MENU           160
#define IDD_GOTO_LINE                   161
#define IDR_EDIT_CONTEXT_MENU1          161
#define IDR_HTML_CONTEXT_MENU           161
#define IDR_MENU_IMAGES                 163
#define IDB_PNG1                        165
#define IDB_MENU_IMAGES_HC              165
#define IDR_LANG_MENU                   166
#define IDB_PNG2                        167
#define IDB_OPTIONS                     167
#define IDD_OPTIONS_PAGE_POPULAR_PAGE   168
#define IDD_OPTIONS_PAGE_RES            170
#define IDD_OPTIONS_PAGE_RESOURCE       170
#define IDD_LANG_EXT                    171
#define IDD_DIALOG1                     172
#define IDD_LANG_EXT_EDIT               172
#define IDD_DIALOG2                     173
#define IDD_SYNEDIT_SET                 173
#define IDD_SYNHTML_SET                 175
#define IDD_SET_CPP                     176
#define IDD_SET_JS                      177
#define IDD_DIALOG3                     178
#define IDD_SET_CPP_FAST                178
#define IDD_TELL_BUG                    179
#define IDD_DIALOG4                     180
#define IDD_SET_CPP_HIGH                180
#define IDD_SET_HTML                    182
#define IDD_SET_HTML_ONE                183
#define IDD_DIALOG5                     184
#define IDD_SET_HTML_TWO                184
#define IDI_ICON1                       186
#define IDI_OUTPUT_BAR_HC               186
#define IDD_DIALOG6                     187
#define IDD_BATCHFORMAT                 187
#define IDD_DIALOG7                     188
#define IDD_SET_PHP                     188
#define IDD_SET_CSS                     191
#define IDD_SET_JSON                    193
#define IDD_SET_SQL                     194
#define IDB_BITMAP1                     196
#define IDB_BITMAP_ABOUT                196
#define IDR_ACCEL_EDIT                  197
#define IDD_DIALOG8                     198
#define IDD_SET_ALL                     198
#define IDD_SET_BASE                    198
#define IDC_COMPANY_URL                 1041
#define IDC_LINE                        1053
#define IDC_LINETIP                     1054
#define IDC_COMBO_COLORSTYLE            1055
#define IDC_COMBO_TIP                   1056
#define IDC_COMBO_TIPSTYLE              1056
#define IDC_BUTTON1                     1057
#define IDC_BUTTON_CHECKUPDATE          1057
#define IDC_LIST_LANGEXT                1058
#define IDC_EDIT1                       1059
#define IDC_EDIT_LANG                   1059
#define IDC_EDIT_BORDER_WIDTH           1059
#define IDC_EDIT_VIEWFORMATTER          1059
#define IDC_EDIT_CPP_INDENT_SPACES      1059
#define IDC_EDIT_HTML_ALT_TEXT          1059
#define IDC_EDIT_ABOUT                  1059
#define IDC_EDIT2                       1060
#define IDC_EDIT_EXT                    1060
#define IDC_EDIT_ADDTITLE               1060
#define IDC_EDIT_HTML_CSS_PREFIX        1060
#define IDC_EDIT_PHP_INDENT_NUMBER      1060
#define IDC_EDIT_CSS_TEMPLATE           1060
#define IDC_COMBO1                      1061
#define IDC_COMBO_LANG                  1061
#define IDC_COMBO_EDITFONT              1061
#define IDC_COMBO_CPP_INDENT_TAB        1061
#define IDC_COMBO_HTML_DOCTYPE          1061
#define IDC_COMBO_PHP_INDENT_TAB        1061
#define IDC_COMBO_CSS_COMPRESSION       1061
#define IDC_STATIC_TIP                  1062
#define IDC_EDIT_VIEWFORMATTER2         1062
#define IDC_BUTTON_DEFAULTEXT           1063
#define IDS_IS_WANTSAVE                 1064
#define IDC_STATIC_LANG                 1064
#define IDS_MSG_GODEFAULT               1065
#define IDC_STATIC_EXT                  1065
#define IDS_LANGUAGE                    1066
#define IDC_COMBO2                      1066
#define IDC_COMBO_EDITSIZE              1066
#define IDC_COMBO_CPP_MIN_CONDITIONAL   1066
#define IDC_COMBO_HTML_MERGE_DIVS       1066
#define IDC_COMBO_PHP_INDENT_STYLE      1066
#define IDC_COMBO_CSS_DISCARD           1066
#define IDS_LANGUAGEEXT                 1067
#define IDC_COMBO3                      1068
#define IDC_COMBO_EDITSTYLE             1068
#define IDC_COMBO_CPP_MAX_INSTATEMENT   1068
#define IDC_COMBO_HTML_MERGE_SPANS      1068
#define IDC_COMBO_CSS_REGROUP           1068
#define IDC_BUTTON_COLOR_BACK           1069
#define IDC_BUTTON2                     1070
#define IDC_BUTTON_COLOR_LINEOUTLINE    1070
#define IDC_LINK_CSDN                   1070
#define IDC_BUTTON_BATCHLOADLIST        1070
#define IDC_BUTTON_LINKME               1070
#define IDC_BUTTON_COLOR_SYN            1071
#define IDC_BUTTON_COLOR_TEXT           1072
#define IDC_BUTTON_COLOR_BACKOUTLINE    1073
#define IDC_BUTTON_COLOR_TYPE           1074
#define IDC_BUTTON_COLOR_LINENUMBER     1075
#define IDC_BUTTON_COLOR_BACKSELACTIVE  1076
#define IDC_BUTTON_COLOR_STRING         1077
#define IDC_BUTTON_COLOR_LINENUMBERBACK 1078
#define IDC_BUTTON_COLOR_BACKSELINACTIVE 1079
#define IDC_BUTTON_COLOR_LINENUMBERBACK2 1079
#define IDC_BUTTON_LINENUMBERBACK_COLOR 1079
#define IDC_BUTTON_COLOR_NUMBER         1080
#define IDC_BUTTON_COLOR_LINENUMBERBACK3 1080
#define IDC_BUTTON_BORDER_COLOR         1080
#define IDC_BUTTON_COLOR_SIDEBAR        1081
#define IDC_BUTTON_SIDEBAR_COLOR        1081
#define IDC_BUTTON_BACKGROUND_COLOR     1081
#define IDC_BUTTON_COLOR_TEXTSELACTIVE  1082
#define IDC_BUTTON_COLOR_CHAR           1083
#define IDC_BUTTON_COLOR_LINK           1084
#define IDC_BUTTON_COLOR_TEXTSELINACTIVE 1085
#define IDC_BUTTON_COLOR_COMMENT        1086
#define IDC_STATIC_EDITFONT             1087
#define IDC_STATIC_EDITSTYLE            1088
#define IDC_STATIC_EDITSIZE             1089
#define IDC_STATIC_COLOR_BACK           1090
#define IDC_STATIC_COLOR_TEXT           1091
#define IDC_STATIC_COLOR_LINENUMBER     1092
#define IDC_STATIC_COLOR_LINENUMBERBACK 1093
#define IDC_STATIC_COLOR_SIDEBAR        1094
#define IDC_STATIC_COLOR_LINK           1095
#define IDC_STATIC_COLOR_LINEOUTLINE    1096
#define IDC_STATIC_COLOR_BACKOUTLINE    1097
#define IDC_STATIC_COLOR_BACKSELACTIVE  1098
#define IDC_STATIC_COLOR_BACKSELINACTIVE 1099
#define IDC_STATIC_COLOR_TEXTSELACTIVE  1100
#define IDC_STATIC_COLOR_TEXTSELINACTIVE 1101
#define IDC_STATIC_COLOR_SYN            1102
#define IDC_STATIC_COLOR_TYPE           1103
#define IDC_STATIC_COLOR_STRING         1104
#define IDC_STATIC_COLOR_NUMBER         1105
#define IDC_STATIC_COLOR_CHAR           1106
#define IDC_STATIC_COLOR_COMMENT        1107
#define IDC_STATIC_FONT                 1108
#define IDC_STATIC_COLOR                1109
#define IDC_CHECK1                      1110
#define IDC_CHECK_SHOW_LINENUMBER       1110
#define IDC_CHECK_BAT_C                 1110
#define IDC_CHECK2                      1111
#define IDC_CHECK_SHOW_SIDEBAR          1111
#define IDC_CHECK_HTML_ADD_XML_SPACE    1111
#define IDC_CHECK_HTML_SHOW_WARNINGS    1111
#define IDC_CHECK_BAT_JAVA              1111
#define IDC_CHECK3                      1112
#define IDC_CHECK_SHOW_BORDER           1112
#define IDC_CHECK_HTML_INDENT_ATTRIBUTES 1112
#define IDC_CHECK_BAT_CS                1112
#define IDC_COMBO4                      1113
#define IDC_COMBO_CPP_ALIGN_POINTER     1113
#define IDC_COMBO_HTML_REPEATED_ATTRIBUTES 1113
#define IDC_COMBO_CSS_OPTIMISE          1113
#define IDC_COMBO5                      1114
#define IDC_COMBO_BORDER_STYLE          1114
#define IDC_COMBO_CPP_ALIGN_REFERENCE   1114
#define IDC_COMBO_HTML_SHOW_BODY_ONLY   1114
#define IDC_COMBO_CSS_CASE              1114
#define IDC_COMBO_HTMLFONT              1115
#define IDC_SPIN1                       1116
#define IDC_SPIN_BORDER_WIDTH           1116
#define IDC_SPIN_CPP_INDENT_SPACES      1116
#define IDC_CHECK_SHOW_LANGTITLE        1117
#define IDC_CHECK_SHOW_ADDTITLE         1119
#define IDC_COMBO_HTMLSTYLE             1120
#define IDS_BORDERSTYLE_DATA            1120
#define IDC_COMBO_HTMLSIZE              1121
#define IDC_STATIC_BORDER_WIDTH         1122
#define IDC_STATIC_BORDER_STYLE         1123
#define IDC_STATIC_BORDER_COLOR         1124
#define IDC_STATIC_LINENUMBER_COLOR     1125
#define IDC_STATIC_BACKGROUND_COLOR     1125
#define IDC_BUTTON_LINENUMBER_COLOR     1126
#define IDC_STATIC_SIDEBAR_COLOR        1127
#define IDC_STATIC_OTHER_SET            1128
#define IDC_STATIC_LINENUMBERBACK_COLOR 1129
#define IDC_EDIT3                       1130
#define IDC_EDIT_LINEHEIGHT             1130
#define IDC_EDIT_HTML_NEW_BLOCKLEVEL_TAGS 1130
#define IDC_EDIT_PHP_FIRST_NUMBER       1130
#define IDC_SPIN_LINEHEIGHT             1131
#define IDC_STATIC_LINEHEIGHT           1132
#define IDC_STATIC_BASIC_SET            1133
#define IDC_STATIC_CPPRECT              1134
#define IDC_LINK_EMAIL                  1135
#define IDC_BUTTON3                     1136
#define IDC_LINK_QQ                     1136
#define IDC_BUTTON_SAVELIST             1136
#define IDC_BUTTON_ABOUT                1136
#define IDC_STATIC_TELLBUG_TOP          1137
#define IDC_STATIC_TELLBUG_TIJIAO       1138
#define IDC_STATIC_EMAIL                1139
#define IDC_STATIC_CSDN                 1140
#define IDC_STATIC_QQ                   1141
#define IDS_EMAIL_TIP                   1142
#define IDC_RADIO1                      1142
#define IDS_CSDN_TIP                    1143
#define IDC_RADIO2                      1143
#define IDS_QQ_TIP                      1144
#define IDC_RADIO3                      1144
#define IDC_RADIO4                      1145
#define IDC_RADIO5                      1146
#define IDC_RADIO6                      1147
#define IDC_RADIO7                      1148
#define IDC_RADIO8                      1149
#define IDC_RADIO9                      1150
#define IDC_RADIO10                     1151
#define IDC_RADIO11                     1152
#define IDC_RADIO12                     1153
#define IDC_RADIO13                     1154
#define IDC_CHECK4                      1155
#define IDC_CHECK_CPP_INDENT_NAMESPACES 1155
#define IDC_CHECK_HTML_INDENT_SPACES    1155
#define IDC_CHECK_BAT_HTML              1155
#define IDC_CHECK_AUTO_COPY             1155
#define IDC_CHECK5                      1156
#define IDC_CHECK_CPP_INDENT_LABEL      1156
#define IDC_CHECK_HTML_MARKUP           1156
#define IDC_CHECK_BAT_XML               1156
#define IDC_CHECK_COPY_CODE             1156
#define IDC_CHECK6                      1157
#define IDC_CHECK_CPP_INDENT_PREPRO     1157
#define IDC_CHECK_HTML_PUNCTUATION_WRAP 1157
#define IDC_CHECK_BAT_JAVAST            1157
#define IDC_CHECK7                      1158
#define IDC_CHECK_CPP_INDENT_           1158
#define IDC_CHECK_CPP_INDENT_COL1COMMENT 1158
#define IDC_CHECK_BAT_PHP               1158
#define IDC_CHECK8                      1159
#define IDC_CHECK_CPP_BREAK_BLOCKS      1159
#define IDC_CHECK_HTML_VERTICAL_SPACE   1159
#define IDC_CHECK_BAT_SQL               1159
#define IDC_CHECK9                      1160
#define IDC_CHECK_CPP_BREAK_ALLBLOCKS   1160
#define IDC_CHECK_HTML_WRAP_ASP         1160
#define IDC_CHECK_PHP_EQUALITY_OPERATORS 1160
#define IDC_CHECK_CSS_DISCARD           1160
#define IDC_CHECK_BAT_JSON              1160
#define IDC_CHECK10                     1161
#define IDC_CHECK_CPP_PAD_OPER          1161
#define IDC_CHECK_HTML_WRAP_ATTRIBUTES  1161
#define IDC_CHECK_PHP_RELATIONAL_OPER   1161
#define IDC_CHECK_CSS_TIMESTAMP         1161
#define IDC_CHECK_BAT_CSS               1161
#define IDC_CHECK11                     1162
#define IDC_CHECK_CPP_PAD_PARENS        1162
#define IDC_CHECK_HTML_WRAP_JSTE        1162
#define IDC_CHECK_PHP_BITWISE_OPER      1162
#define IDC_CHECK_CSS_SILENT            1162
#define IDC_CHECK12                     1163
#define IDC_CHECK_CPP_PAD_PARENSOUT     1163
#define IDC_CHECK_HTML_WRAP_PHP         1163
#define IDC_CHECK_PHP_ASSIGNMENT_OPER   1163
#define IDC_CHECK13                     1164
#define IDC_CHECK_CPP_PAD_PARENSIN      1164
#define IDC_CHECK_HTML_WRAP_SCRIPT_LITERALS 1164
#define IDC_CHECK_PHP_MAP_OPER          1164
#define IDC_CHECK14                     1165
#define IDC_CHECK_CPP_PAD_HEADER        1165
#define IDC_CHECK_HTML_WRAP_SECTIONS    1165
#define IDC_CHECK_PHP_REMOVE_COMMENTS   1165
#define IDC_CHECK15                     1166
#define IDC_CHECK_CPP_UNPAD_PARENS      1166
#define IDC_CHECK_HTML_ASCII_CHARS      1166
#define IDC_CHECK_PHP_COMMENT_STRUCTURES 1166
#define IDC_CHECK16                     1167
#define IDC_CHECK_CPP_DEL_EMPTYLINES    1167
#define IDC_CHECK_HTML_FIX_URI          1167
#define IDC_CHECK_PHP_ALIGN_ASSIGNMENTS 1167
#define IDC_CHECK17                     1168
#define IDC_CHECK_CPP_FILL_EMPTYLINES   1168
#define IDC_CHECK_HTML_HIDE_COMMENTS    1168
#define IDC_CHECK18                     1169
#define IDC_CHECK_CPP_BREAK_CLOSINGBRACKETS 1169
#define IDC_CHECK_HTML_HIDE_ENDTAGS     1169
#define IDC_CHECK_PHP_REMOVE_EMPTYLINES 1169
#define IDC_CHECK19                     1170
#define IDC_CHECK_CPP_ADD_BRACKETS      1170
#define IDC_CHECK_HTML_INDENT_CDATA     1170
#define IDC_CHECK_PHP_REMOVE_SEMICOLON  1170
#define IDC_CHECK20                     1171
#define IDC_CHECK_CPP_ADD_ONELINEBRACKETS 1171
#define IDC_CHECK_HTML_INPUT_XML        1171
#define IDC_CHECK_PHP_INDENT_EMPTYLINES 1171
#define IDC_CHECK21                     1172
#define IDC_CHECK_CPP_KEEP_ONELINEBLOCKS 1172
#define IDC_CHECK_HTML_JOIN_CLASSES     1172
#define IDC_CHECK_PHP_REWRITE_PERL_COMM 1172
#define IDC_CHECK22                     1173
#define IDC_CHECK_CPP_KEEP_ONELINESTATE 1173
#define IDC_CHECK_HTML_JOIN_STYLES      1173
#define IDC_CHECK_PHP_REWRITE_SHORT_TAG 1173
#define IDC_CHECK23                     1174
#define IDC_CHECK_CPP_CONVERT_TABS      1174
#define IDC_CHECK_HTML_LITERAL_ATTRIBUTES 1174
#define IDC_CHECK_PHP_ASP_TAGS          1174
#define IDC_CHECK25                     1176
#define IDC_CHECK_CPP_BREAK_ELSEIFS     1176
#define IDC_CHECK_HTML_LOWER_LITERALS   1176
#define IDC_CHECK_PHP_QUIET             1176
#define IDC_CHECK_CPP_INDENT_CLASS      1177
#define IDC_CHECK_CPP_INDENT_SWITCH     1178
#define IDC_CHECK_CPP_INDENT_CASE       1179
#define IDC_CHECK24                     1180
#define IDC_CHECK_HTML_LOGICAL_EMPHASIS 1180
#define IDC_CHECK_PHP_SHORT_TAGS        1180
#define IDC_CHECK26                     1181
#define IDC_CHECK27                     1182
#define IDC_CHECK28                     1183
#define IDC_CHECK_HTML_NCR              1183
#define IDC_CHECK29                     1184
#define IDC_CHECK_HTML_NUMERIC_ENTITIES 1184
#define IDC_CHECK30                     1185
#define IDC_CHECK_HTML_OUTPUT_HTML      1185
#define IDC_CHECK31                     1186
#define IDC_CHECK_HTML_OUTPUT_XHTML     1186
#define IDC_CHECK32                     1187
#define IDC_CHECK_HTML_OUTPUT_XML       1187
#define IDC_CHECK33                     1188
#define IDC_CHECK_HTML_PRESERVE_ENTITIES 1188
#define IDC_CHECK34                     1189
#define IDC_CHECK_HTML_QUOTE_AMPERSAND  1189
#define IDC_CHECK35                     1190
#define IDC_CHECK_HTML_QUOTE_MARKS      1190
#define IDC_CHECK36                     1191
#define IDC_CHECK_HTML_QUOTE_NBSP       1191
#define IDC_CHECK37                     1192
#define IDC_CHECK_HTML_REPLACE_COLOR    1192
#define IDC_CHECK38                     1193
#define IDC_CHECK39                     1194
#define IDC_CHECK_HTML_UPPERCASE_ATTRIBUTES 1194
#define IDC_CHECK40                     1195
#define IDC_CHECK_HTML_UPPERCASE_TAGS   1195
#define IDC_CHECK41                     1196
#define IDC_CHECK_HTML_WORD_2000        1196
#define IDC_STATIC_HTMLRECT             1197
#define IDC_EDIT4                       1198
#define IDC_EDIT_HTML_NEW_EMPTY_TAGS    1198
#define IDC_EDIT5                       1199
#define IDC_EDIT_HTML_NEW_INLINE_TAGS   1199
#define IDC_EDIT6                       1200
#define IDC_EDIT_HTML_NEW_PRE_TAGS      1200
#define IDC_COMBO6                      1201
#define IDC_COMBO_HTML_INDENT           1201
#define IDC_COMBO7                      1202
#define IDC_COMBO_HTML_SORT_ATTRIBUTES  1202
#define IDC_EDIT7                       1203
#define IDC_EDIT_HTML_INDENT_SPACES     1203
#define IDC_EDIT8                       1204
#define IDC_EDIT_HTML_TAB_SIZE          1204
#define IDC_EDIT9                       1205
#define IDC_EDIT_HTML_WRAP              1205
#define IDC_SPIN2                       1206
#define IDC_SPIN3                       1207
#define IDC_CHECK_HTML_ADD_XML_DECL     1208
#define IDC_CHECK_HTML_ANCHOR_AS_NAME   1209
#define IDC_CHECK_HTML_ASSUME_XML_PROCINS 1210
#define IDC_CHECK_HTML_BARE             1211
#define IDC_CHECK_HTML_CLEAN            1212
#define IDC_CHECK_HTML_DECORATE_INFERRED_UL 1213
#define IDC_CHECK_HTML_DROP_EMPTY_PARAS 1214
#define IDC_CHECK_HTML_DROP_FONT_TAGS   1215
#define IDC_CHECK_HTML_DROP_PROPRIETARY_ATTS 1216
#define IDC_CHECK_HTML_ENCLOSE_BLOCK_TEXT 1217
#define IDC_CHECK_HTML_ENCLOSE_TEXT     1218
#define IDC_CHECK_HTML_ESCAPE_CDATA     1219
#define IDC_CHECK_HTML_FIX_BACKSLASH    1220
#define IDC_CHECK_HTML_FIX_BAD_COMMENTS 1221
#define IDC_COMBO_HTML_CHAR_ENCODING    1222
#define IDC_COMBO_HTML_INPUT_ENCODING   1223
#define IDC_COMBO_HTML_OUTPUT_ENCODING  1224
#define IDC_EDIT10                      1225
#define IDC_EDIT_HTML_SHOW_ERRORS       1225
#define IDC_SPIN4                       1226
#define IDC_CHECK_HTML_BREAK_BEFORE_BR  1227
#define IDC_CHECK_HTML_FORCE_OUTPUT     1228
#define IDC_LIST1                       1229
#define IDC_PROGRESS1                   1230
#define IDC_PROGRESS_BATCHPGR           1230
#define IDC_BUTTON4                     1231
#define IDC_BUTTON_DOBATCH              1231
#define IDC_STATIC_BATCHSELLAN          1232
#define IDC_STATIC_BATCHSELFILES        1233
#define IDC_LIST2                       1234
#define IDC_LIST_BATCHFILE              1234
#define IDC_BUTTON_BARCHADDFILES        1235
#define IDC_CHECK_PHP_SPACE_STRUCTURES  1236
#define IDC_CHECK_PHP_INDENT_CASE       1237
#define IDC_CHECK_PHP_BRACKETS          1238
#define IDC_CHECK_PHP_EMPTY_BRACKETS    1239
#define IDC_CHECK_PHP_BLOCK_BRACKETS    1240
#define IDC_CHECK_PHP_EMPTY_BLOCK       1241
#define IDC_CHECK_PHP_MATH_OPERATORS    1242
#define IDC_CHECK_PHP_LOGICAL_OPERATORS 1243
#define IDC_SPIN_PHP_INDENT_NUMBER      1244
#define IDC_SPIN_PHP_FIRST_NUMBER       1245
#define IDC_COMBO_JS_INDENT_TAB         1246
#define IDC_COMBO_JS_INDENT_STYLE       1247
#define IDC_EDIT_JS_INDENT_NUMBER       1248
#define IDC_SPIN_JS_INDENT_NUMBER       1249
#define IDC_CHECK_CSS_PRESERVE          1250
#define IDC_EDIT_SQL_SUB_NUMBER         1250
#define IDC_CHECK_CSS_SELECTORS         1251
#define IDC_SPIN_SQL_SUB_NUMBER2        1251
#define IDC_SPIN_SQL_SUB_NUMBER         1251
#define IDC_CHECK_CSS_PROPERTIES        1252
#define IDC_CHECK_CSS_REMOVELAST        1253
#define IDC_CHECK_CSS_REMOVESLASH       1254
#define IDC_CHECK_CSS_COLORS            1255
#define IDC_CHECK_CSS_FONTWEIGHT        1256
#define IDC_CHECK_CSS_LOWERCASE         1257
#define IDC_EDIT_JSON_INDENT_NUMBER     1258
#define IDC_SPIN_JSON_INDENT_NUMBER     1259
#define IDC_COMBO_SQL_INDENT_TAB        1260
#define IDC_EDIT_SQL_INDENT_NUMBER      1261
#define IDC_SPIN_SQL_INDENT_NUMBER      1262
#define IDC_CHECK_SQL_ENDLINE           1263
#define IDC_STATIC_ABOUT                1264
#define IDC_STATIC_DROPTIP              1265
#define IDC_STATIC_STYLECOLOR           1266
#define IDC_STATIC_STYLESCREEN          1267
#define IDC_STATIC_STYLELANG            1268
#define IDC_STATIC_RESUPDATE            1269
#define IDC_STATIC_LINKME               1270
#define IDC_STATIC_VIEWFORMATTER        1271
#define IDC_STATIC_WUHUAN               1272
#define IDC_STATIC_VERSION              1273
#define IDC_PROPLIST_LOCATION           1274
#define ID_VIEW_TOOLBARS                32771
#define ID_WINDOW_MANAGER               32825
#define ID_VIEW_APPLOOK_2000            32826
#define ID_VIEW_APPLOOK_XP              32827
#define ID_VIEW_APPLOOK_2003            32828
#define ID_VIEW_APPLOOK_WIN_XP          32829
#define ID_VIEW_APPLOOK_VS2005          32830
#define ID_VIEW_APPLOOK_2007            32831
#define ID_VIEW_APPLOOK_2007_1          32832
#define ID_VIEW_APPLOOK_2007_2          32833
#define ID_VIEW_APPLOOK_2007_3          32834
#define ID_VIEW_APPLOOK_VS2008          32835
#define ID_VIEW_APPLOOK_VS2010          32836
#define ID_VIEW_APPLOOK_2010_1          32837
#define ID_VIEW_APPLOOK_2010_2          32838
#define ID_VIEW_APPLOOK_2010_3          32839
#define ID_VIEW_APPLOOK_WIN7            32840
#define ID_MDI_NEW_VERT_GROUP           32841
#define ID_MDI_NEW_HORZ_TAB_GROUP       32842
#define ID_MDI_MOVE_TO_PREV_GROUP       32843
#define ID_MDI_CANCEL                   32844
#define ID_MDI_MOVE_TO_NEXT_GROUP       32845
#define ID_TOOLS_OPTIONS                32847
#define ID_STATUSBAR_PANE1              32848
#define ID_STATUSBAR_PANE2              32849
#define ID__32850                       32850
#define ID__32851                       32851
#define ID__32852                       32852
#define ID__32853                       32853
#define ID__                            32854
#define ID__32855                       32855
#define ID__32856                       32856
#define ID_EDIT_GOTO_LINE               32857
#define ID_EDIT_HIDESELECTION           32858
#define ID_DUMMY_32861                  32861
#define ID_DUMMY_32862                  32862
#define ID_DUMMY_32863                  32863
#define ID_FILE_OTHER_CLOSE             32864
#define ID_FILE_PATH                    32865
#define ID_FILEDIR_OPEN                 32866
#define ID_32869                        32869
#define ID__32870                       32870
#define ID_32871                        32871
#define ID_FORMAT                       32872
#define ID_FASTFORMAT                   32873
#define ID_32874                        32874
#define ID_32875                        32875
#define ID_32876                        32876
#define ID_32877                        32877
#define ID_32878                        32878
#define ID_EDIT_STOPHIDINGCURRENT       32879
#define ID_EDIT_TOGGLEOUTLINING         32880
#define ID_EDIT_TOGGLEALLOUTLINING      32881
#define ID_EDIT_COLLAPSETODEFINITIONS   32882
#define ID_EDIT_STOPOUTLINING           32883
#define ID_A_ACTIONSCRIPT               32884
#define ID_A_ADA                        32885
#define ID_A_ASM                        32886
#define ID_A_ASP                        32887
#define ID_32888                        32888
#define ID_LANG                         32889
#define ID_BATCH                        32890
#define ID_C_COBOL                      32891
#define ID_C_C                          32892
#define ID_C_C32893                     32893
#define ID_C_CSS                        32894
#define ID_D                            32895
#define ID_FORTRAN                      32896
#define ID_H_HASKELL                    32897
#define ID_H_HTML                       32898
#define ID_J_JAVA                       32899
#define ID_J_JAVASCRIPT                 32900
#define ID_J_JSON                       32901
#define ID_J_JSP                        32902
#define ID_L_LISP                       32903
#define ID_L_LUA                        32904
#define ID_P_PASCAL                     32905
#define ID_OBJECTIVE                    32906
#define ID_NORMALTEXT                   32907
#define ID_INI                          32908
#define ID_P_PERL                       32909
#define ID_P_PHP                        32910
#define ID_P_PYTHON                     32911
#define ID_RUBY                         32912
#define ID_SQL                          32913
#define ID_V_VB                         32914
#define ID_V_VERILOG                    32915
#define ID_V_VHDL                       32916
#define ID_XML                          32917
#define ID_A_AUTOHOTKEY                 32918
#define ID_A_AUTOIT                     32919
#define ID_32920                        32920
#define ID_NOW_LANG                     32921
#define ID__32922                       32922
#define ID__COPY_HTMLSRC                32923
#define ID_COPY_HTMLSRC                 32924
#define ID_32925                        32925
#define ID_LANGEXT                      32926
#define ID_32927                        32927
#define ID_SETEDIT                      32928
#define ID_32929                        32929
#define ID_HTMLTOBLOG                   32930
#define ID_SETHTML                      32931
#define ID_32932                        32932
#define ID_32933                        32933
#define ID_EXPORTREG                    32934
#define ID_IMPORTREG                    32935
#define ID_32936                        32936
#define ID_TELLBUG                      32937
#define ID_32938                        32938
#define ID_ONLINEHELP                   32939
#define ID_32940                        32940
#define ID_INDENT_MIN                   32941
#define ID_32942                        32942
#define ID_INDENT_ADD                   32943
#define ID_32944                        32944
#define ID_COMMENT_DO                   32945
#define ID_32946                        32946
#define ID_COMMENT_NOT                  32947
#define ID_32948                        32948
#define ID_SELFORMAT                    32949
#define ID_SETFORMATTER                 32950
#define ID_OUTPUT_BAR                   32951
#define ID_32952                        32952
#define ID_BATCHFORMAT                  32953

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        199
#define _APS_NEXT_COMMAND_VALUE         32977
#define _APS_NEXT_CONTROL_VALUE         1275
#define _APS_NEXT_SYMED_VALUE           108
#endif
#endif
